str1=str.upper("subhash")
print(str1)
str2=str.lower("subhash gawade")
print(str2)
str3=str.title("welcome to sunbeam")
print(str3)
str4=str.capitalize("welcome to sunbeam")
print(str4)
str5=str.swapcase("hEY sUBHASH tHANK u fOR vISITING uS")
print(str5)
